replicaCount: 1

image:
  repository: 192.168.56.10:5000/my-gitops-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: my-gitops-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
